language: r
cache: packages
matrix:
  include:
#  - r: oldrel
#    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
#  - r: release
#    os: osx
r_packages:
 - covr
before_install:
  - . <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_dynverse
install:
 - use_dynverse_devel
 - install_cran devtools
 - install_cran covr
 - Rscript -e 'install.packages(c("data.table", "car"))'
 - install_withdeps
after_success:
 - R -e 'covr::codecov()'
