language: r
sudo: true
cache: packages
warnings_are_errors: true
cache:
  timeout: 2000
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/R/Library
before_install:
 - source <( curl --insecure https://raw.githubusercontent.com/dynverse/dynmethods/master/.travis_install_python.sh ) # use travis's own python
install:
 - pip3 install --user --upgrade --only-binary=numpy,scipy numpy scipy        # many packages
 - pip3 install --user --upgrade umap                                         # umapr
install:
   - R -e 'setRepositories(ind = 1:2); devtools::install(dependencies = TRUE, upgrade = TRUE)'
