language: r
sudo: required
dist: trusty
bioc_required: true
cache:
  timeout: 2000
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/R/Library
warnings_are_errors: true
addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libreadline-dev
      - imagemagick
      - libfftw3-dev
      - libudunits2-dev
      - libblas-dev
      - liblapack-dev
before_install:
 - source <( curl --insecure https://raw.githubusercontent.com/dynverse/dynmethods/master/.travis_install_python.sh ) # use travis's own python
install:
 - pip3 install --user --upgrade --only-binary=numpy,scipy numpy scipy
 - pip3 install --user --upgrade umap-learn
 - if [ `git branch | grep '* master' | wc -l` == 0 ]; then sed -i 's#\(dynverse/[^, ]*\)#\1@devel#' DESCRIPTION; fi
 - R -e 'if ("devtools" %in% rownames(installed.packages())) update.packages(oldPkgs = "devtools", ask = FALSE) else install.packages("devtools")'
 - R -e 'devtools::install_github(c("r-lib/rlang", "tidyverse/ggplot2"))'
 - R -e 'devtools::install_cran(c("covr", "knitr"))'
 - R -e 'setRepositories(ind = 1:2); devtools::install(dependencies = TRUE, upgrade = TRUE)'
after_success:
 - R -e 'covr::codecov()'
