language: r
cache: packages
matrix:
  include:
  - r: oldrel
    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
r_packages:
 - covr
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_dynverse
after_success:
 - R -e 'covr::codecov()'
