language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
warnings_are_errors: true
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_dynverse
install:
 - use_dynverse_devel
 - install_cran devtools
 - install_cran covr
 - install_withdeps
after_success:
 - R -e 'covr::codecov()'
