language: r
sudo: false
cache: packages
warnings_are_errors: true
before_install:
  - pip install --user umap-learn
install:
   - R -e 'setRepositories(ind = 1:2); devtools::install(dependencies = TRUE, upgrade = TRUE)'
